"use client";

import { useLocale } from "./i18n";

/**
 * All UI copy, both locales. Data (plates, IDs, what a driver actually said)
 * lives in mockData and does NOT come through here — see the note in i18n.tsx
 * about why a translated transcript would be a lie.
 */

export const STRINGS = {
  en: {
    poweredBy: "Powered by",
    live: "Live",
    back: "Back",
    am: "AM",
    najm: "Najm",
    najmLatin: "NAJM",

    seats: {
      caller: "Caller Experience",
      support: "Customer Support",
      investigator: "Investigator",
      ops: "Operations Center",
    },

    support: {
      role: "Customer Support",
      eyebrow: "Customer Support",
      strapline: "The same assistant, pointed at Najm's other front door",
      opening: "How can I help you tonight?",
      pickHint: "Tap what you would say",
      detected: "Intent detected",
      confidence: "confidence",
      unclear: "I want to get you to the right place. Which of these is it?",
      intents: {
        status: "Status inquiry",
        complaint: "Complaint",
        objection: "Objection",
        unclear: "Not yet clear",
      },
      // status
      statusTitle: "Your accident report",
      statusRef: "Reference",
      statusState: "Status",
      statusStateValue: "Under review",
      latestUpdate: "Latest update",
      // complaint
      reviewTitle: "Review before it is submitted",
      summary: "Structured summary",
      category: "Category",
      priority: "Priority",
      queue: "Assigned queue",
      slaLabel: "Expected response",
      sla: "10 working days",
      submit: "Submit",
      edit: "Edit",
      submittedComplaint: "Complaint submitted",
      submittedObjection: "Objection recorded",
      reference: "Reference number",
      // objection
      objectionRoute: "This request will be handled through Najm's objection workflow.",
      objectionRoadmap:
        "Objection processing is on the roadmap. For now it enters the complaint workflow as a structured request.",
      // close
      seeOps: "See what the Najm team receives",
      restart: "Start over",
      generated: "Structured by the assistant — not free text",
    },

    departments: {
      claims: "Claims Operations",
      liability: "Liability Review",
      field: "Field Assessment",
      care: "Customer Care",
    },

    langName: { ar: "Arabic", ur: "Urdu", en: "English" },

    /* ── caller phone ── */
    caller: {
      assistant: "Smart Assistant",
      detected: "auto-detected",
      idAsk: "ID / Iqama number",
      edit: "Edit",
      confirmId: "Confirm number",
      partyA: "First party",
      partyB: "Other party",
      verified: "Verified",
      addPhoto: "Add a photo of the other vehicle",
      continue: "Continue",
      evidenceAsk: "Please photograph the vehicle registration",
      uploaded: "Uploaded • Registration",
      ocrTitle: "Data extraction",
      ocrTag: "From document",
      fields: "fields",
      readbackTitle: "Confirm the details",
      readbackSub: "Review the summary before the report is filed",
      readbackConfirm: "Confirm details",
      readbackHelper: "Or say “edit” to correct anything",
      parties: "Parties",
      twoParties: "Two parties",
      location: "Location",
      locationValue: "King Fahd Road, Riyadh",
      injuries: "Injuries",
      none: "None",
      insurance: "Insurance",
      insurer: "Tawuniya",
      insVerified: "Verified",
      idMasked: "ID",
      plate: "plate",
      ticketTitle: "Report created",
      ticketRefLabel: "Reference number",
      ticketStatus: "Under review",
      ticketCompleteness: "Case file completeness",
      ticketComplete: "fields complete",
      ticketNote: "Ask about your case any time — available 24/7",
      statusNight: "2:14 AM — late-night status check",
      statusAsk: "Where has my case got to?",
      statusAnswerA: "Your report ",
      statusAnswerB: " is now under review.",
      statusLine: "Status: under review",
      nextStep: "Next step:",
      nextStepBody: "A damage assessor will be assigned within 24 hours; you will be notified the moment it happens.",
      answeredAt: "Answered instantly • 2:14 AM",
      handoff: "See what the Najm team sees",
      complaintCta: "File a complaint",
      complaintFiled: "Complaint filed",
      complaintRef: "Complaint reference",
      complaintType: "Type",
      complaintUrgency: "Urgency",
      complaintClassified: "Classified at submission",
      complaintSla: "A reply within 10 working days",
    },

    chrome: {
      eyebrow: "Caller Experience",
      strapline: "A voice accident report — a delivery driver's story",
      next: "Next ›",
      prev: "‹ Back",
      keys: "space · next  ·  R · reset  ·  I · investigator",
    },

    beats: [
      "Greeting in Arabic",
      "Language detected — switch to Urdu",
      "Guided intake",
      "Documents and automatic extraction",
      "Confirming the details",
      "Report created",
      "Status query",
    ],

    ocrFields: {
      plate: "Plate number",
      owner: "Owner name",
      vehicle: "Vehicle",
      insurer: "Insurer",
    },

    /* ── console ── */
    nav: { dashboard: "Dashboard", investigators: "Investigators", cases: "Cases", complaints: "Complaints" },

    ops: {
      role: "Operations Center",
      dashTitle: "Operations dashboard",
      dashSub: "Riyadh — night shift",
      aiTitle: "Assistant performance",
      aiSub: "Measured across today's calls",
      emergencyBand: "Active emergency — needs immediate dispatch",
      emergencyCta: "Open report",
      liveTitle: "Calls in progress",
      liveEmpty: "No calls in progress",
      captured: "fields captured",
      attentionTitle: "Needs you",
      attentionSub: "Human escalations from investigators",
      attentionEmpty: "Nothing waiting on the supervisor",
      queueTitle: "Queue health",
      queueSub: "Where work is piling up — by age, not by count",
      rosterTitle: "Investigator load",
      activityTitle: "Recent activity",
      available: "Available",
      loaded: "Loaded",
      full: "At capacity",
      away: "Away",
      oldest: "Oldest case",
      assign: "Assign",
      unassignedTitle: "Ready, not assigned",
      detectedDuring: "Detected by the assistant during intake at",
      neverQueued: "This case never entered the investigation queue.",
      takeOver: "Take over",
      takenOver: "Supervisor on the call",
      dispatch: "Dispatch",
      dispatched: "Dispatched",
      dispatchHint: "Send help now, then open the report",
    },

    queueStages: {
      awaiting_party_b: { label: "Awaiting the other party", hint: "One account cannot settle fault" },
      ready: { label: "Ready, unassigned", hint: "Complete file with no owner" },
      awaiting_info: { label: "Awaiting information", hint: "The assistant is calling back" },
    },

    inv: {
      role: "Investigator",
      inboxTitle: "My casework",
      inboxSub: "Ordered by what blocks a decision, not by age",
      ready: "Ready to decide",
      notReady: "Not ready to decide",
      conflicts: "unresolved conflicts",
      conflict: "unresolved conflict",
      missing: "missing fields",
      waitingB: "The other party's account has not arrived",
      complete: "File complete",
      noConflict: "No conflict between the accounts",
      summaryTitle: "AI summary",
      compareTitle: "Contradiction table",
      compareSub: "Compare the two accounts before deciding",
      narrativeA: "Party A's account",
      narrativeB: "Party B's account",
      claim: "Item",
      verdict: "Verdict",
      pA: "Party A",
      pB: "Party B",
      evidenceTitle: "Evidence",
      fieldsTitle: "Extracted fields",
      transcript: "Verbatim transcript",
      timeline: "Activity log",
      assistant: "Najm Assistant",
      engine: "SARJ AI",
      actContinue: "Continue investigation",
      actRequest: "Request more information",
      actResolve: "Issue the verdict",
      actEscalate: "Escalate to supervisor",
      noCompare: "Cannot compare on one account. The assistant will attach the other party's report the moment it arrives.",
      progressLogged: "Progress logged",
      classification: "Automatic classification",
      tagAccident: "Accident report",
      tagDetected: "auto-detected",
      tagNoInjuries: "No injuries",
      tagEmergency: "Emergency — injury mentioned",
    },

    claimVerdict: {
      agree: "Agree",
      conflict: "Conflict",
      onlyA: "Party A only",
      onlyB: "Party B only",
    },

    status: {
      intake: "Intake",
      awaiting_party_b: "Awaiting other party",
      ready: "Ready",
      investigating: "Under investigation",
      awaiting_info: "Awaiting information",
      escalated: "Escalated",
      emergency: "Emergency",
      resolved: "Resolved",
    },

    escalate: {
      title: "Escalate to supervisor",
      intro: "The supervisor receives the whole file. Do not re-explain the case.",
      modeLabel: "Mode",
      advice: "Ask for advice",
      adviceHint: "The case stays yours",
      transfer: "Transfer the case",
      transferHint: "Ownership moves to the supervisor",
      reasonLabel: "Reason",
      noteLabel: "Note for the supervisor",
      notePlaceholder: "Why do you need help?",
      bundleTitle: "What the supervisor receives — automatically",
      send: "Send escalation",
      cancel: "Cancel",
      sent: "Escalated — the supervisor has the complete file",
      bundle: [
        "AI summary",
        "Both verbatim transcripts",
        "Contradiction table",
        "Documents and OCR results",
        "Extracted fields",
        "Activity log",
      ],
    },

    reasons: {
      conflict: "Conflicting accounts",
      liability: "Liability unclear",
      fraud: "Suspected fraud",
      complex: "Complex case",
    },

    requestInfo: {
      title: "Request more information",
      intro: "The Najm assistant will call the chosen party and ask a targeted question.",
      partyLabel: "Party",
      topicLabel: "Topic",
      missingFields: "Missing fields in the file",
      send: "Ask the assistant to call",
      cancel: "Cancel",
      willCall: "The assistant will call",
    },

    resolve: {
      title: "Issue the verdict",
      faultLabel: "Apportion liability",
      faultHint: "Party A's share. Party B carries the remainder.",
      riskTitle: "Objection risk",
      riskBody:
        "A conflict between the two accounts is still open. A verdict issued over an open conflict is the one most likely to return through the objection committee.",
      confirm: "Issue verdict",
      cancel: "Cancel",
      issued: "Verdict issued",
    },

    liabilityPrefix: "Liability — ",

    packet: {
      title: "Escalation file",
      from: "From",
      note: "Investigator's note",
      modeAdvice: "Advice requested — ownership stays with the investigator",
      modeTransfer: "Ownership transferred",
      reply: "Reply with advice",
      replyPlaceholder: "Your advice for the investigator…",
      reassign: "Reassign",
      takeOver: "Take the case",
      emergencyReason: "Why this went to emergency",
    },

    aiPerf: {
      langTitle: "Language distribution",
      langNote: "Work is not routed by language — the assistant absorbs it.",
      metrics: [
        { label: "Containment (eligible)", value: "86%", note: "Calls completed with zero agent minutes" },
        { label: "File completeness", value: "94%", note: "Reports with every mandatory field" },
        { label: "OCR success", value: "91%", note: "Registrations read without intervention" },
        { label: "Human handoff accuracy", value: "100%", note: "Injury, human requested, or details uncollectable" },
      ],
      langs: [
        { label: "Arabic", pct: 57 },
        { label: "Urdu", pct: 29 },
        { label: "English", pct: 14 },
      ],
    },

    complaints: {
      title: "Complaints",
      sub: "Triaged by the assistant at submission — not one flat queue",
      empty: "No open complaints",
      ref: "Reference",
      about: "About",
      type: "Type",
      urgency: "Urgency",
      filed: "Filed",
      sla: "SLA",
      daysLeft: "days left",
      dayLeft: "day left",
      atRisk: "At risk",
      said: "In the caller's words",
      picked: "Caller selected",
      corrected: "Corrected by the assistant",
      confidence: "Confidence",
      department: "Department",
      types: {
        delay: "Processing delay",
        conduct: "Assessor conduct",
        verdict: "Verdict dispute",
        service: "Service quality",
      },
      urgencies: { high: "High", medium: "Medium", low: "Low" },
      taxonomyNote: "Taxonomy is illustrative — to be replaced with Najm's own.",
    },

    ledger: {
      ref: "Reference",
      status: "Status",
      lang: "Language",
      completeness: "Completeness",
      investigator: "Investigator",
      age: "Age",
    },

    people: {
      inv1: "Faisal Al-Harbi",
      inv2: "Noura Al-Anzi",
      inv3: "Saad Al-Mutairi",
      inv4: "Hind Al-Zahrani",
      supervisor: "Riyadh Operations",
      supervisorRole: "Supervisor",
    },

    ago: (v: string) => `${v} ago`,
    min: "m",
    hr: "h",
  },

  ar: {
    poweredBy: "Powered by",
    live: "مباشر",
    back: "رجوع",
    am: "ص",
    najm: "نجم",
    najmLatin: "NAJM",

    seats: {
      caller: "تجربة المتصل",
      support: "خدمة العملاء",
      investigator: "مساحة المحقق",
      ops: "مركز العمليات",
    },

    support: {
      role: "خدمة العملاء",
      eyebrow: "خدمة العملاء",
      strapline: "المساعد نفسه، على باب نجم الآخر",
      opening: "كيف أقدر أساعدك الليلة؟",
      pickHint: "اختر ما ستقوله",
      detected: "تم تحديد الطلب",
      confidence: "ثقة",
      unclear: "أبغى أوصّلك للجهة الصحيحة. أيّها طلبك؟",
      intents: {
        status: "استعلام حالة",
        complaint: "شكوى",
        objection: "اعتراض",
        unclear: "غير واضح بعد",
      },
      statusTitle: "بلاغ حادثك",
      statusRef: "الرقم المرجعي",
      statusState: "الحالة",
      statusStateValue: "قيد المراجعة",
      latestUpdate: "آخر تحديث",
      reviewTitle: "راجِع قبل الإرسال",
      summary: "ملخّص مُهيكل",
      category: "التصنيف",
      priority: "الأولوية",
      queue: "الجهة المسؤولة",
      slaLabel: "مدة الرد المتوقعة",
      sla: "١٠ أيام عمل",
      submit: "إرسال",
      edit: "تعديل",
      submittedComplaint: "تم تسجيل الشكوى",
      submittedObjection: "تم تسجيل الاعتراض",
      reference: "الرقم المرجعي",
      objectionRoute: "سيُعالَج هذا الطلب عبر مسار الاعتراضات في نجم.",
      objectionRoadmap:
        "معالجة الاعتراضات ضمن خارطة الطريق. حاليًا يدخل مسار الشكاوى كطلب مُهيكل.",
      seeOps: "شاهد ما يصل فريق نجم",
      restart: "من البداية",
      generated: "هيكلَه المساعد — لا نص حر",
    },

    departments: {
      claims: "عمليات المطالبات",
      liability: "مراجعة المسؤولية",
      field: "المعاينة الميدانية",
      care: "خدمة العملاء",
    },

    langName: { ar: "العربية", ur: "أردو", en: "الإنجليزية" },

    caller: {
      assistant: "المساعد الذكي",
      detected: "كُشف تلقائيًا",
      idAsk: "رقم الهوية / الإقامة",
      edit: "تعديل",
      confirmId: "تأكيد الرقم",
      partyA: "الطرف الأول",
      partyB: "الطرف الآخر",
      verified: "موثّق",
      addPhoto: "أضف صورة للمركبة الأخرى",
      continue: "متابعة",
      evidenceAsk: "صوّر استمارة السيارة من فضلك",
      uploaded: "تم الرفع • استمارة",
      ocrTitle: "استخراج البيانات",
      ocrTag: "من المستند",
      fields: "حقول",
      readbackTitle: "تأكيد التفاصيل",
      readbackSub: "راجع الملخّص قبل إنشاء البلاغ",
      readbackConfirm: "أكّد التفاصيل",
      readbackHelper: "أو قُل «عدّل» لتصحيح أي معلومة",
      parties: "الأطراف",
      twoParties: "طرفان",
      location: "الموقع",
      locationValue: "طريق الملك فهد، الرياض",
      injuries: "الإصابات",
      none: "لا يوجد",
      insurance: "التأمين",
      insurer: "التعاونية",
      insVerified: "مُتحقق",
      idMasked: "هوية",
      plate: "لوحة",
      ticketTitle: "تم إنشاء البلاغ",
      ticketRefLabel: "الرقم المرجعي",
      ticketStatus: "قيد المراجعة",
      ticketCompleteness: "اكتمال البيانات",
      ticketComplete: "حقول مكتملة",
      ticketNote: "اسأل عن حالة قضيتك في أي وقت — الخدمة متاحة ٢٤/٧",
      statusNight: "٢:١٤ ص — استعلام متأخر ليلًا",
      statusAsk: "وين وصلت قضيتي؟",
      statusAnswerA: "بلاغك ",
      statusAnswerB: " قيد المراجعة الآن.",
      statusLine: "الحالة: قيد المراجعة",
      nextStep: "الخطوة التالية:",
      nextStepBody: "تعيين مُقيّم أضرار خلال ٢٤ ساعة، وسيصلك إشعار فور الإسناد.",
      answeredAt: "تم الرد فورًا • ٢:١٤ ص",
      handoff: "شاهد ما رآه فريق نجم",
      complaintCta: "تقديم شكوى",
      complaintFiled: "تم تسجيل الشكوى",
      complaintRef: "رقم الشكوى",
      complaintType: "النوع",
      complaintUrgency: "الأولوية",
      complaintClassified: "صُنّفت لحظة التقديم",
      complaintSla: "الرد خلال ١٠ أيام عمل",
    },

    chrome: {
      eyebrow: "تجربة المتصل",
      strapline: "بلاغ حادث صوتي — قصة سائق توصيل",
      next: "التالي ›",
      prev: "‹ السابق",
      keys: "space · التالي  ·  R · إعادة  ·  I · المحقق",
    },

    beats: [
      "الترحيب بالعربية",
      "كشف اللغة والتحوّل إلى الأردو",
      "الاستقصاء الموجَّه",
      "المستندات والاستخراج الآلي",
      "تأكيد التفاصيل",
      "إنشاء البلاغ",
      "استعلام الحالة",
    ],

    ocrFields: {
      plate: "رقم اللوحة",
      owner: "اسم المالك",
      vehicle: "نوع المركبة",
      insurer: "شركة التأمين",
    },

    nav: { dashboard: "لوحة المعلومات", investigators: "المحققون", cases: "القضايا", complaints: "الشكاوى" },

    ops: {
      role: "مركز العمليات",
      dashTitle: "لوحة العمليات",
      dashSub: "الرياض — الوردية الليلية",
      aiTitle: "أداء المساعد",
      aiSub: "مقيسًا على مكالمات اليوم",
      emergencyBand: "طوارئ نشطة — تتطلب تحويلًا فوريًا",
      emergencyCta: "فتح البلاغ",
      liveTitle: "مكالمات جارية الآن",
      liveEmpty: "لا توجد مكالمات جارية",
      captured: "حقول مُلتقطة",
      attentionTitle: "يتطلب انتباهك",
      attentionSub: "تصعيدات بشرية من المحققين",
      attentionEmpty: "لا شيء ينتظر المشرف",
      queueTitle: "صحة الطابور",
      queueSub: "أين يتكدّس العمل — بالعمر، لا بالعدد",
      rosterTitle: "حِمل المحققين",
      activityTitle: "آخر الإجراءات",
      available: "متاح",
      loaded: "محمّل",
      full: "مكتمل الحمل",
      away: "غير متاح",
      oldest: "أقدم قضية",
      assign: "إسناد",
      unassignedTitle: "جاهزة ولم تُسند",
      detectedDuring: "رصده الذكاء أثناء الاستقبال في",
      neverQueued: "لم تدخل هذه القضية طابور التحقيق.",
      takeOver: "تولّي المكالمة",
      takenOver: "المشرف على الخط",
      dispatch: "إرسال الطوارئ",
      dispatched: "تم الإرسال",
      dispatchHint: "أرسل المساعدة الآن، ثم افتح البلاغ",
    },

    queueStages: {
      awaiting_party_b: { label: "بانتظار الطرف الآخر", hint: "لا يمكن البتّ برواية واحدة" },
      ready: { label: "جاهزة ولم تُسند", hint: "ملف مكتمل بلا مالك" },
      awaiting_info: { label: "بانتظار معلومات", hint: "الذكاء يعاود الاتصال" },
    },

    inv: {
      role: "مساحة المحقق",
      inboxTitle: "صندوق قضاياي",
      inboxSub: "مرتّبة بما يعيق القرار، لا بالأقدمية",
      ready: "جاهزة للقرار",
      notReady: "غير جاهزة للقرار",
      conflicts: "تعارض غير محسوم",
      conflict: "تعارض غير محسوم",
      missing: "حقل ناقص",
      waitingB: "لم تصل رواية الطرف الآخر",
      complete: "الملف مكتمل",
      noConflict: "لا تعارض بين الروايتين",
      summaryTitle: "ملخص الذكاء",
      compareTitle: "جدول التعارضات",
      compareSub: "قارن الروايتين قبل القرار",
      narrativeA: "رواية الطرف أ",
      narrativeB: "رواية الطرف ب",
      claim: "البند",
      verdict: "الحكم",
      pA: "الطرف أ",
      pB: "الطرف ب",
      evidenceTitle: "الأدلة",
      fieldsTitle: "الحقول المستخرجة",
      transcript: "النص الحرفي",
      timeline: "سجل الإجراءات",
      assistant: "مساعد نجم",
      engine: "SARJ AI",
      actContinue: "متابعة التحقيق",
      actRequest: "طلب معلومات إضافية",
      actResolve: "إصدار القرار",
      actEscalate: "تصعيد للمشرف",
      noCompare: "لا يمكن المقارنة برواية واحدة. الذكاء سيربط بلاغ الطرف الآخر بالقضية فور وروده.",
      progressLogged: "سُجّلت المتابعة",
      classification: "التصنيف الآلي",
      tagAccident: "بلاغ حادث",
      tagDetected: "كُشف تلقائيًا",
      tagNoInjuries: "بدون إصابات",
      tagEmergency: "طوارئ — ذكر إصابة",
    },

    claimVerdict: {
      agree: "متطابق",
      conflict: "متعارض",
      onlyA: "ذكره الطرف أ فقط",
      onlyB: "ذكره الطرف ب فقط",
    },

    status: {
      intake: "استقبال",
      awaiting_party_b: "بانتظار الطرف الآخر",
      ready: "جاهزة للتحقيق",
      investigating: "قيد التحقيق",
      awaiting_info: "بانتظار معلومات",
      escalated: "مُصعّدة",
      emergency: "طوارئ",
      resolved: "منتهية",
    },

    escalate: {
      title: "تصعيد للمشرف",
      intro: "المشرف سيصل إليه الملف كاملًا. لا تُعِد شرح القضية.",
      modeLabel: "الوضع",
      advice: "طلب مشورة",
      adviceHint: "تبقى القضية باسمك",
      transfer: "نقل القضية",
      transferHint: "تنتقل الملكية للمشرف",
      reasonLabel: "السبب",
      noteLabel: "ملاحظة للمشرف",
      notePlaceholder: "لماذا تحتاج المساعدة؟",
      bundleTitle: "ما سيصل للمشرف — تلقائيًا",
      send: "إرسال التصعيد",
      cancel: "إلغاء",
      sent: "تم التصعيد — الملف كامل عند المشرف",
      bundle: [
        "ملخص الذكاء",
        "النصوص الحرفية للطرفين",
        "جدول التعارضات",
        "المستندات ونتائج OCR",
        "الحقول المستخرجة",
        "سجل الإجراءات",
      ],
    },

    reasons: {
      conflict: "تعارض في الروايات",
      liability: "مسؤولية غير واضحة",
      fraud: "اشتباه احتيال",
      complex: "حالة معقدة",
    },

    requestInfo: {
      title: "طلب معلومات إضافية",
      intro: "سيتصل مساعد نجم بالطرف المحدّد ويسأله سؤالًا موجّهًا.",
      partyLabel: "الطرف",
      topicLabel: "الموضوع",
      missingFields: "حقول ناقصة في الملف",
      send: "اطلب من الذكاء الاتصال",
      cancel: "إلغاء",
      willCall: "سيتصل مساعد نجم بـ",
    },

    resolve: {
      title: "إصدار القرار",
      faultLabel: "توزيع المسؤولية",
      faultHint: "نصيب الطرف أ. والباقي على الطرف ب.",
      riskTitle: "خطر اعتراض",
      riskBody:
        "يوجد تعارض غير محسوم بين الروايتين. القرار الصادر على تعارض مفتوح هو أكثر ما يعود عبر لجنة الاعتراض.",
      confirm: "إصدار القرار",
      cancel: "إلغاء",
      issued: "صدر القرار",
    },

    liabilityPrefix: "المسؤولية — ",

    packet: {
      title: "ملف التصعيد",
      from: "من",
      note: "ملاحظة المحقق",
      modeAdvice: "طلب مشورة — الملكية باقية مع المحقق",
      modeTransfer: "نقل ملكية",
      reply: "رد بمشورة",
      replyPlaceholder: "مشورتك للمحقق…",
      reassign: "إعادة تعيين",
      takeOver: "تولّي القضية",
      emergencyReason: "سبب التحويل للطوارئ",
    },

    aiPerf: {
      langTitle: "توزيع اللغات",
      langNote: "لا يُوجَّه العمل حسب اللغة — الذكاء يستوعبها.",
      metrics: [
        { label: "نسبة الاحتواء (المؤهلة)", value: "٨٦٪", note: "مكالمات اكتملت بلا دقيقة موظف" },
        { label: "اكتمال الملف", value: "٩٤٪", note: "بلاغات بكل الحقول الإلزامية" },
        { label: "نجاح OCR", value: "٩١٪", note: "استمارات قُرئت دون تدخل" },
        { label: "دقة التحويل للبشر", value: "١٠٠٪", note: "إصابة، أو طلب موظف، أو تعذّر جمع المعلومات" },
      ],
      langs: [
        { label: "عربي", pct: 57 },
        { label: "أردو", pct: 29 },
        { label: "إنجليزي", pct: 14 },
      ],
    },

    complaints: {
      title: "الشكاوى",
      sub: "يصنّفها الذكاء لحظة التقديم — لا طابور واحد بلا فرز",
      empty: "لا توجد شكاوى مفتوحة",
      ref: "الرقم المرجعي",
      about: "بخصوص",
      type: "النوع",
      urgency: "الأولوية",
      filed: "وقت التقديم",
      sla: "المهلة",
      daysLeft: "يوم متبقٍ",
      dayLeft: "يوم متبقٍ",
      atRisk: "على وشك التجاوز",
      said: "بكلام المتصل",
      picked: "اختاره المتصل",
      corrected: "صحّحه المساعد",
      confidence: "الثقة",
      department: "الجهة",
      types: {
        delay: "تأخر المعالجة",
        conduct: "سلوك المُقيّم",
        verdict: "اعتراض على القرار",
        service: "جودة الخدمة",
      },
      urgencies: { high: "عالية", medium: "متوسطة", low: "منخفضة" },
      taxonomyNote: "التصنيف توضيحي — يُستبدل بتصنيف نجم الفعلي.",
    },

    ledger: {
      ref: "الرقم المرجعي",
      status: "الحالة",
      lang: "اللغة",
      completeness: "الاكتمال",
      investigator: "المحقق",
      age: "العمر",
    },

    people: {
      inv1: "فيصل الحربي",
      inv2: "نورة العنزي",
      inv3: "سعد المطيري",
      inv4: "هند الزهراني",
      supervisor: "عمليات الرياض",
      supervisorRole: "المشرف",
    },

    ago: (v: string) => `منذ ${v}`,
    min: "د",
    hr: "س",
  },
} as const;

export type Str = (typeof STRINGS)["en"];

export function useT(): Str {
  const { locale } = useLocale();
  return STRINGS[locale] as Str;
}

/** "منذ ٤٢ د" / "42m ago" — one formatter, both locales. */
export function useAge() {
  const t = useT();
  const { n } = useLocale();
  return (min: number) => {
    if (min < 60) return t.ago(`${n(min)}${t.min}`);
    const h = Math.floor(min / 60);
    const m = min % 60;
    return t.ago(m ? `${n(h)}${t.hr} ${n(m)}${t.min}` : `${n(h)}${t.hr}`);
  };
}

/** Clock times are stored bare ("2:14") and dressed per locale. */
export function useClock() {
  const t = useT();
  const { n } = useLocale();
  return (hhmm: string) => `${n(hhmm)} ${t.am}`;
}
